
services:
  - type: web
    name: monroe-bot-dashboard
    env: node
    plan: starter
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: API_SECRET
        generateValue: true
      - key: BOT_API_URL
        value: https://monroe-bot.onrender.com
      - key: PORT
        value: 5000
