services:
  - type: web
    name: monroe-bot-dashboard
    env: node
    plan: starter
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: monroe-bot-db
          property: connectionString
      - key: API_SECRET
        generateValue: true
      - key: BOT_API_URL
        value: https://monroe-bot.onrender.com
    disk:
      name: monroe-dashboard-disk
      mountPath: /app/data
      sizeGB: 1

databases:
  - name: monroe-bot-db
    plan: starter
    region: oregon